channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - bcftools=1.3.1
  - bwa=0.7.12
  - fastqc=0.11.7
  - gatk=3.7
  - graphviz=2.40.1
  - python=3.5.1
  - pyyaml=3.11
  - r=3.5.0
  - samtools=1.3.1
  - snakemake=3.11.0
